version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-increment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_portal
    ports:
      - "5056:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - increment-network

  backend:
    build: ./Backend
    container_name: backend-increment
    ports:
      - "3089:3089"
    depends_on:
      - postgres
    networks:
      - increment-network

  employee-increment:
    build: ./Employee-Increment
    container_name: employee-increment
    ports:
      - "9049:80"
    depends_on:
      - backend
    networks:
      - increment-network

  hr-increment:
    build: ./HR-Increment
    container_name: hr-increment
    ports:
      - "9050:80"
    depends_on:
      - backend
    networks:
      - increment-network

volumes:
  postgres-data:

networks:
  increment-network:

